-- Nawi Saadi Trip Portal — complete schema.
--
-- Runs against the SAME Supabase project as the marketing site, in the
-- Supabase SQL editor. Every table is prefixed `trip_` so nothing here can
-- collide with the website's `leads`, `events` or `media` tables. The two
-- applications share a database and share nothing else.
--
-- ---------------------------------------------------------------------------
-- THE SECURITY DECISION THAT SHAPES EVERYTHING BELOW
-- ---------------------------------------------------------------------------
--
-- A customer opens their trip with a link and no password. That is the right
-- product decision — a tourist will not create an account to find their
-- driver — but it means the link itself is the credential, and it decides how
-- every policy in this file has to work.
--
-- The tempting design is to let the browser read the trip directly with the
-- anon key, filtered by the token. Do not do this. PostgREST would happily
-- accept `?select=*` with no token filter at all, and the anon key is public by
-- definition — it ships inside the JavaScript bundle. One person reading the
-- page source would then be able to download every customer's itinerary, phone
-- number, hotel booking and passport-adjacent document in the database. That is
-- not a theoretical risk; it is the single most common way portals like this
-- leak.
--
-- So: the anon and authenticated roles are granted NOTHING on these tables.
-- Not select, not insert. Every read happens server-side in the portal's SSR
-- handler using the service role key, which never reaches the browser, after
-- that handler has looked up the token itself. The token is checked in code
-- that the customer cannot bypass, and a wrong token renders a 404.
--
-- The explicit REVOKE statements at the foot of this file are what enforce it.
-- They are also there so that a future change made in the Supabase dashboard,
-- which is how the website's `leads` policy was once quietly loosened, shows up
-- as a difference against this file.

-- ---------------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------------
--
-- Kept separate from the website's `leads` table on purpose. A lead is someone
-- who asked a question; this is someone who has paid and is travelling. They
-- have different lifecycles, different retention needs, and conflating them
-- means a marketing export can accidentally carry a travelling customer's
-- passport details.

create table if not exists public.trip_customers (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  full_name   text not null,
  phone       text,
  whatsapp    text,
  email       text,
  nationality text,
  -- Free-text for the office: dietary needs, mobility, who to call first.
  notes       text
);

create index if not exists trip_customers_name_idx on public.trip_customers (lower(full_name));

-- ---------------------------------------------------------------------------
-- Trips
-- ---------------------------------------------------------------------------

do $$ begin
  create type trip_state as enum ('draft', 'confirmed', 'in_progress', 'completed', 'cancelled');
exception when duplicate_object then null;
end $$;

create table if not exists public.trips (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- The human reference the office uses on the phone: NST-260928-001.
  trip_code     text not null unique,

  customer_id   uuid references public.trip_customers (id) on delete set null,

  title         text,
  destination   text not null,
  start_date    date not null,
  end_date      date not null,
  status        trip_state not null default 'draft',

  -- The credential in the URL.
  --
  -- Generated by the application with crypto.randomUUID-grade entropy, not by
  -- a sequence, and deliberately NOT the trip_code. NST-260928-001 is
  -- guessable by design — it encodes a date and a counter — so using it as the
  -- link would let anyone walk the whole customer list by incrementing the last
  -- three digits. They are two different identifiers doing two different jobs.
  tracking_token text not null unique,

  -- Draft/publish. A trip is built over several sittings and must not be
  -- half-visible to the customer in the meantime; the portal refuses to render
  -- a trip whose published_at is null.
  published_at   timestamptz,

  hero_image     text,
  pax_adults     int not null default 1,
  pax_children   int not null default 0,

  -- Shown in the portal's emergency panel. Defaults are applied by the
  -- application from the office numbers rather than hardcoded here, so a
  -- changed office line does not need a migration.
  emergency_name  text,
  emergency_phone text,

  created_by     text,

  constraint trips_dates_ordered check (end_date >= start_date),
  constraint trips_code_shape    check (length(trip_code) between 3 and 40),
  -- 32 hex characters minimum. A short token is a guessable token, and this is
  -- the only thing standing between a URL and someone's hotel voucher.
  constraint trips_token_length  check (length(tracking_token) >= 32)
);

create index if not exists trips_token_idx   on public.trips (tracking_token);
create index if not exists trips_status_idx  on public.trips (status, start_date desc);
create index if not exists trips_created_idx on public.trips (created_at desc);

-- ---------------------------------------------------------------------------
-- Days
-- ---------------------------------------------------------------------------

create table if not exists public.trip_days (
  id           uuid primary key default gen_random_uuid(),
  trip_id      uuid not null references public.trips (id) on delete cascade,
  day_number   int  not null,
  date         date,
  title        text not null,
  summary      text,
  cover_image  text,
  -- A day can be published while the next one is still being written.
  published    boolean not null default false,
  created_at   timestamptz not null default now(),

  unique (trip_id, day_number)
);

create index if not exists trip_days_trip_idx on public.trip_days (trip_id, day_number);

-- ---------------------------------------------------------------------------
-- Steps
-- ---------------------------------------------------------------------------
--
-- The structured spine of a day: "Step 1, Airport Arrival, 14:30, Terminal 3".
-- Content hangs off a step as blocks (next table). Splitting it this way is
-- what lets the office reorder a day by dragging three steps instead of
-- fourteen blocks, while still allowing any content inside each one.

create table if not exists public.trip_steps (
  id            uuid primary key default gen_random_uuid(),
  trip_day_id   uuid not null references public.trip_days (id) on delete cascade,
  step_number   int  not null,
  title         text not null,
  description   text,

  -- Clock time as text, not `time`. An itinerary says "around 14:30", "after
  -- lunch", "on arrival" — a typed time column forces the office to invent
  -- precision it does not have, and then the portal displays a false certainty
  -- the customer will hold us to.
  time_label    text,
  duration      text,

  location_name text,
  latitude      double precision,
  longitude     double precision,

  created_at    timestamptz not null default now(),

  unique (trip_day_id, step_number),
  constraint trip_steps_lat_range check (latitude  is null or latitude  between  -90 and  90),
  constraint trip_steps_lng_range check (longitude is null or longitude between -180 and 180)
);

create index if not exists trip_steps_day_idx on public.trip_steps (trip_day_id, step_number);

-- ---------------------------------------------------------------------------
-- Blocks — the page builder
-- ---------------------------------------------------------------------------
--
-- One table, one `kind`, one jsonb payload. The alternative — a column per
-- content type, or a table per content type — means a migration every time the
-- office wants a new kind of block, which defeats the entire purpose of
-- building an admin they can use without a developer.
--
-- The trade is that the payload's shape is enforced in TypeScript rather than
-- by the database. That is the correct place for it: the shapes change with the
-- UI, and a CHECK constraint on jsonb keys would have to be migrated in step
-- with every admin release.

do $$ begin
  create type trip_block_kind as enum (
    'text',        -- a paragraph
    'heading',     -- a subheading within a step
    'image',       -- one photograph, with a caption
    'gallery',     -- several photographs
    'video',       -- the meeting-point clip; the whole reason this exists
    'map',         -- an embedded location
    'driver',      -- a driver card, referencing trip_drivers
    'hotel',
    'flight',
    'ticket',      -- an attraction ticket or voucher
    'document',    -- a PDF, referencing trip_documents
    'contact',
    'notice',      -- "please be ready 10 minutes early"
    'emergency',
    'link',
    'checklist',
    'invoice'      -- embeds a published invoice; the table is in 0002
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.trip_blocks (
  id            uuid primary key default gen_random_uuid(),
  trip_step_id  uuid not null references public.trip_steps (id) on delete cascade,
  position      int  not null,
  kind          trip_block_kind not null,

  -- Everything the block needs to render. Bounded, because this is written
  -- from a browser form and a jsonb column with no ceiling is an invitation.
  payload       jsonb not null default '{}'::jsonb,

  created_at    timestamptz not null default now(),

  constraint trip_blocks_payload_size check (pg_column_size(payload) <= 32768)
);

create index if not exists trip_blocks_step_idx on public.trip_blocks (trip_step_id, position);

-- ---------------------------------------------------------------------------
-- Drivers
-- ---------------------------------------------------------------------------
--
-- A row per driver, not per assignment, because the same driver works many
-- trips and re-typing their plate number for each one is how a wrong plate
-- reaches a customer standing in an airport car park.

create table if not exists public.trip_drivers (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  full_name    text not null,
  photo        text,
  phone        text,
  whatsapp     text,
  vehicle      text,
  plate_number text,
  languages    text,
  active       boolean not null default true
);

create index if not exists trip_drivers_active_idx on public.trip_drivers (active, lower(full_name));

-- ---------------------------------------------------------------------------
-- Live progress — the part the customer actually refreshes for
-- ---------------------------------------------------------------------------
--
-- Append-only. The current state is the most recent row, and the history is
-- the whole point: "driver arrived 14:12, customer picked up 14:31" is what
-- settles a dispute about a late transfer three weeks later. Storing only a
-- current status on `trips` would overwrite exactly the evidence worth keeping.

do $$ begin
  create type trip_progress_stage as enum (
    'booked',
    'documents_ready',
    'driver_assigned',
    'driver_on_the_way',
    'driver_arrived',
    'customer_picked_up',
    'transfer_started',
    'destination_reached',
    'checked_in',
    'activity_in_progress',
    'activity_complete',
    'departure_transfer',
    'trip_complete'
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.trip_progress (
  id          bigserial primary key,
  trip_id     uuid not null references public.trips (id) on delete cascade,
  -- Optional: which day or step this progress concerns. Null means the trip
  -- as a whole, which is what a "documents ready" update is.
  trip_day_id uuid references public.trip_days (id) on delete set null,
  stage       trip_progress_stage not null,
  note        text,
  driver_id   uuid references public.trip_drivers (id) on delete set null,
  -- Whether the customer sees this entry. Some updates are internal.
  visible     boolean not null default true,
  created_at  timestamptz not null default now(),
  created_by  text
);

create index if not exists trip_progress_trip_idx on public.trip_progress (trip_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Documents
-- ---------------------------------------------------------------------------

do $$ begin
  create type trip_doc_visibility as enum ('always', 'requires_verification', 'staff_only');
exception when duplicate_object then null;
end $$;

create table if not exists public.trip_documents (
  id          uuid primary key default gen_random_uuid(),
  trip_id     uuid not null references public.trips (id) on delete cascade,
  name        text not null,
  -- Object path inside the private `trip-docs` bucket. Never a public URL:
  -- the portal mints a short-lived signed URL at render time instead, so a
  -- voucher link pasted into a group chat stops working within the hour.
  file_path   text not null,
  doc_type    text,
  visibility  trip_doc_visibility not null default 'always',
  position    int not null default 0,
  bytes       int,
  created_at  timestamptz not null default now()
);

create index if not exists trip_documents_trip_idx on public.trip_documents (trip_id, position);

-- ---------------------------------------------------------------------------
-- Portal analytics
-- ---------------------------------------------------------------------------
--
-- Deliberately narrow. This records that a page was opened and which section
-- was looked at, so the office can tell whether a customer has actually read
-- the pickup instructions before ringing to ask where the driver is. That is a
-- real operational need and it justifies exactly this much.
--
-- What is NOT recorded, and must not be added later without a reason better
-- than curiosity: precise location, anything typed, any identifier that
-- outlives the trip. The portal shows the customer a plain notice saying the
-- office can see when they open it; a system that watches people without
-- telling them is a different thing wearing the same name.

create table if not exists public.trip_views (
  id          bigserial primary key,
  trip_id     uuid not null references public.trips (id) on delete cascade,
  created_at  timestamptz not null default now(),
  -- 'open' | 'day' | 'driver' | 'documents' | 'video' | 'document_open' | ...
  event       text not null,
  detail      text,
  device      text,
  -- Per-visit, from sessionStorage. Dies with the tab and is never joined to a
  -- name — enough to count visits, not enough to build a profile.
  session_id  text,

  constraint trip_views_event_len   check (length(event)  <= 40),
  constraint trip_views_detail_len  check (detail is null or length(detail) <= 200),
  constraint trip_views_session_len check (session_id is null or length(session_id) <= 64)
);

create index if not exists trip_views_trip_idx on public.trip_views (trip_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Audit trail
-- ---------------------------------------------------------------------------
--
-- Who changed what, when. The case this exists for: a pickup point is edited
-- from Exit 2 to Exit 3, the customer waits at the wrong exit, and the office
-- needs to know whether that edit happened before or after the customer opened
-- the page — and who made it.
--
-- Filled by trigger rather than by the application, so an admin screen added
-- later cannot forget to write to it. The triggers below cover the tables
-- where a wrong value reaches a traveller.

create table if not exists public.trip_audit (
  id          bigserial primary key,
  created_at  timestamptz not null default now(),
  table_name  text not null,
  row_id      text not null,
  trip_id     uuid,
  action      text not null,          -- insert | update | delete
  -- Only the fields that actually changed, old and new. Storing whole rows
  -- makes the history unreadable at exactly the moment someone needs to read
  -- it quickly.
  changes     jsonb not null default '{}'::jsonb,
  actor       text
);

create index if not exists trip_audit_trip_idx  on public.trip_audit (trip_id, created_at desc);
create index if not exists trip_audit_table_idx on public.trip_audit (table_name, row_id, created_at desc);

-- The acting admin's email, set per-connection by the application as
-- `set_config('app.actor', ..., true)`. Falls back to the database role, which
-- at least distinguishes a service-role write from a dashboard edit.
create or replace function public.trip_audit_actor() returns text
language sql stable as $$
  select coalesce(nullif(current_setting('app.actor', true), ''), current_user);
$$;

create or replace function public.trip_audit_capture() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  diff    jsonb := '{}'::jsonb;
  new_j   jsonb;
  old_j   jsonb;
  k       text;
  owner   uuid;
begin
  if (tg_op = 'INSERT') then
    new_j := to_jsonb(new);
    diff  := jsonb_build_object('new', new_j);
  elsif (tg_op = 'DELETE') then
    old_j := to_jsonb(old);
    diff  := jsonb_build_object('old', old_j);
  else
    new_j := to_jsonb(new);
    old_j := to_jsonb(old);
    -- Only changed keys. `updated_at` is excluded because it changes on every
    -- write and would make every entry look like a real edit.
    for k in select jsonb_object_keys(new_j) loop
      if k <> 'updated_at' and (new_j -> k) is distinct from (old_j -> k) then
        diff := diff || jsonb_build_object(k, jsonb_build_object('from', old_j -> k, 'to', new_j -> k));
      end if;
    end loop;
    -- Nothing of substance changed; do not record a row.
    if diff = '{}'::jsonb then
      return new;
    end if;
  end if;

  -- Which trip this belongs to, so the history can be shown on one screen.
  -- Each table reaches `trips` by a different route.
  begin
    if tg_table_name = 'trips' then
      owner := coalesce((new_j ->> 'id')::uuid, (old_j ->> 'id')::uuid);
    elsif tg_table_name in ('trip_days', 'trip_documents', 'trip_invoices') then
      owner := coalesce((new_j ->> 'trip_id')::uuid, (old_j ->> 'trip_id')::uuid);
    elsif tg_table_name = 'trip_steps' then
      select d.trip_id into owner from public.trip_days d
       where d.id = coalesce((new_j ->> 'trip_day_id')::uuid, (old_j ->> 'trip_day_id')::uuid);
    elsif tg_table_name = 'trip_blocks' then
      select d.trip_id into owner from public.trip_steps s
        join public.trip_days d on d.id = s.trip_day_id
       where s.id = coalesce((new_j ->> 'trip_step_id')::uuid, (old_j ->> 'trip_step_id')::uuid);
    end if;
  exception when others then
    owner := null;
  end;

  insert into public.trip_audit (table_name, row_id, trip_id, action, changes, actor)
  values (
    tg_table_name,
    coalesce(new_j ->> 'id', old_j ->> 'id', ''),
    owner,
    lower(tg_op),
    diff,
    public.trip_audit_actor()
  );

  if (tg_op = 'DELETE') then return old; end if;
  return new;
end $$;

drop trigger if exists trips_audit          on public.trips;
drop trigger if exists trip_days_audit      on public.trip_days;
drop trigger if exists trip_steps_audit     on public.trip_steps;
drop trigger if exists trip_blocks_audit    on public.trip_blocks;
drop trigger if exists trip_documents_audit on public.trip_documents;

create trigger trips_audit          after insert or update or delete on public.trips          for each row execute function public.trip_audit_capture();
create trigger trip_days_audit      after insert or update or delete on public.trip_days      for each row execute function public.trip_audit_capture();
create trigger trip_steps_audit     after insert or update or delete on public.trip_steps     for each row execute function public.trip_audit_capture();
create trigger trip_blocks_audit    after insert or update or delete on public.trip_blocks    for each row execute function public.trip_audit_capture();
create trigger trip_documents_audit after insert or update or delete on public.trip_documents for each row execute function public.trip_audit_capture();

-- Keep `trips.updated_at` honest, so the admin list can sort by real activity.
create or replace function public.trips_touch() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trips_touch_updated on public.trips;
create trigger trips_touch_updated before update on public.trips
  for each row execute function public.trips_touch();

-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------
--
-- Both buckets are PRIVATE. The website's `media` bucket is public because it
-- holds marketing photographs meant to be seen; these hold one named
-- customer's meeting-point photograph and their hotel voucher, which are not
-- the same kind of thing at all.
--
-- The portal serves them as signed URLs minted per request in the SSR handler.
-- That costs one signing call per asset and means a link forwarded to a group
-- chat expires rather than becoming a permanent public URL.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'trip-media', 'trip-media', false,
  209715200,  -- 200MB: a 30-second phone clip of an airport exit is ~40MB
  array[
    'image/jpeg','image/png','image/webp','image/avif','image/heic',
    'video/mp4','video/quicktime','video/webm'
  ]
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'trip-docs', 'trip-docs', false,
  26214400,  -- 25MB
  array['application/pdf','image/jpeg','image/png','image/webp']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- No storage policies for anon or authenticated are created, deliberately.
-- Uploads and signing both happen server-side with the service role, which
-- bypasses RLS. A leaked anon key cannot list a bucket, read a voucher, or
-- replace a driver's photograph.
drop policy if exists "trip media anon read"  on storage.objects;
drop policy if exists "trip docs anon read"   on storage.objects;

-- ---------------------------------------------------------------------------
-- Row Level Security: on everywhere, with no public policy anywhere
-- ---------------------------------------------------------------------------
--
-- RLS is enabled and then no policy is granted to anon or authenticated. The
-- effect is a default deny: PostgREST returns an empty set for a read and a
-- 401/403 for a write, whatever query is sent. The service role bypasses RLS
-- entirely, which is how the portal and admin read anything at all.

alter table public.trip_customers enable row level security;
alter table public.trips          enable row level security;
alter table public.trip_days      enable row level security;
alter table public.trip_steps     enable row level security;
alter table public.trip_blocks    enable row level security;
alter table public.trip_drivers   enable row level security;
alter table public.trip_progress  enable row level security;
alter table public.trip_documents enable row level security;
alter table public.trip_views     enable row level security;
alter table public.trip_audit     enable row level security;

-- Belt as well as braces. RLS governs row visibility; these REVOKEs remove the
-- table privilege itself, so even a policy added by accident in the dashboard
-- cannot open a read path. Any future loosening has to undo a line in this
-- file, which makes it visible in review.
revoke all on public.trip_customers from anon, authenticated;
revoke all on public.trips          from anon, authenticated;
revoke all on public.trip_days      from anon, authenticated;
revoke all on public.trip_steps     from anon, authenticated;
revoke all on public.trip_blocks    from anon, authenticated;
revoke all on public.trip_drivers   from anon, authenticated;
revoke all on public.trip_progress  from anon, authenticated;
revoke all on public.trip_documents from anon, authenticated;
revoke all on public.trip_views     from anon, authenticated;
revoke all on public.trip_audit     from anon, authenticated;

-- The admin list view, `trip_overview`, lives in 0002: it reports each trip's
-- outstanding balance, so it has to be created after the invoice tables exist.
