/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomizedToursRouteImport } from './routes/customized-tours'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DubaiRouteImport } from './routes/dubai'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UaeRouteImport } from './routes/uae'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as HolidaysIndexRouteImport } from './routes/holidays.index'
import { Route as HolidaysSlugRouteImport } from './routes/holidays.$slug'
import { Route as HolidaysSlugItineraryDotpdfRouteImport } from './routes/holidays.$slug.itinerary[.]pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizedToursRoute = CustomizedToursRouteImport.update({
  id: '/customized-tours',
  path: '/customized-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DubaiRoute = DubaiRouteImport.update({
  id: '/dubai',
  path: '/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UaeRoute = UaeRouteImport.update({
  id: '/uae',
  path: '/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysIndexRoute = HolidaysIndexRouteImport.update({
  id: '/holidays/',
  path: '/holidays/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysSlugRoute = HolidaysSlugRouteImport.update({
  id: '/holidays/$slug',
  path: '/holidays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysSlugItineraryDotpdfRoute =
  HolidaysSlugItineraryDotpdfRouteImport.update({
    id: '/itinerary.pdf',
    path: '/itinerary.pdf',
    getParentRoute: () => HolidaysSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/customized-tours': typeof CustomizedToursRoute
  '/deals': typeof DealsRoute
  '/dubai': typeof DubaiRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/uae': typeof UaeRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/holidays/$slug': typeof HolidaysSlugRouteWithChildren
  '/activities/': typeof ActivitiesIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/holidays/': typeof HolidaysIndexRoute
  '/holidays/$slug/itinerary.pdf': typeof HolidaysSlugItineraryDotpdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/customized-tours': typeof CustomizedToursRoute
  '/deals': typeof DealsRoute
  '/dubai': typeof DubaiRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/uae': typeof UaeRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/holidays/$slug': typeof HolidaysSlugRouteWithChildren
  '/activities': typeof ActivitiesIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/holidays': typeof HolidaysIndexRoute
  '/holidays/$slug/itinerary.pdf': typeof HolidaysSlugItineraryDotpdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/customized-tours': typeof CustomizedToursRoute
  '/deals': typeof DealsRoute
  '/dubai': typeof DubaiRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/uae': typeof UaeRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/holidays/$slug': typeof HolidaysSlugRouteWithChildren
  '/activities/': typeof ActivitiesIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/holidays/': typeof HolidaysIndexRoute
  '/holidays/$slug/itinerary.pdf': typeof HolidaysSlugItineraryDotpdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/customized-tours'
    | '/deals'
    | '/dubai'
    | '/plan'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/uae'
    | '/activities/$slug'
    | '/countries/$slug'
    | '/holidays/$slug'
    | '/activities/'
    | '/countries/'
    | '/holidays/'
    | '/holidays/$slug/itinerary.pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/customized-tours'
    | '/deals'
    | '/dubai'
    | '/plan'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/uae'
    | '/activities/$slug'
    | '/countries/$slug'
    | '/holidays/$slug'
    | '/activities'
    | '/countries'
    | '/holidays'
    | '/holidays/$slug/itinerary.pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/customized-tours'
    | '/deals'
    | '/dubai'
    | '/plan'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/uae'
    | '/activities/$slug'
    | '/countries/$slug'
    | '/holidays/$slug'
    | '/activities/'
    | '/countries/'
    | '/holidays/'
    | '/holidays/$slug/itinerary.pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CustomizedToursRoute: typeof CustomizedToursRoute
  DealsRoute: typeof DealsRoute
  DubaiRoute: typeof DubaiRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UaeRoute: typeof UaeRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  HolidaysSlugRoute: typeof HolidaysSlugRouteWithChildren
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  HolidaysIndexRoute: typeof HolidaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customized-tours': {
      id: '/customized-tours'
      path: '/customized-tours'
      fullPath: '/customized-tours'
      preLoaderRoute: typeof CustomizedToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai': {
      id: '/dubai'
      path: '/dubai'
      fullPath: '/dubai'
      preLoaderRoute: typeof DubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uae': {
      id: '/uae'
      path: '/uae'
      fullPath: '/uae'
      preLoaderRoute: typeof UaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays/': {
      id: '/holidays/'
      path: '/holidays'
      fullPath: '/holidays/'
      preLoaderRoute: typeof HolidaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays/$slug': {
      id: '/holidays/$slug'
      path: '/holidays/$slug'
      fullPath: '/holidays/$slug'
      preLoaderRoute: typeof HolidaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays/$slug/itinerary.pdf': {
      id: '/holidays/$slug/itinerary.pdf'
      path: '/itinerary.pdf'
      fullPath: '/holidays/$slug/itinerary.pdf'
      preLoaderRoute: typeof HolidaysSlugItineraryDotpdfRouteImport
      parentRoute: typeof HolidaysSlugRoute
    }
  }
}

interface HolidaysSlugRouteChildren {
  HolidaysSlugItineraryDotpdfRoute: typeof HolidaysSlugItineraryDotpdfRoute
}

const HolidaysSlugRouteChildren: HolidaysSlugRouteChildren = {
  HolidaysSlugItineraryDotpdfRoute: HolidaysSlugItineraryDotpdfRoute,
}

const HolidaysSlugRouteWithChildren = HolidaysSlugRoute._addFileChildren(
  HolidaysSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CustomizedToursRoute: CustomizedToursRoute,
  DealsRoute: DealsRoute,
  DubaiRoute: DubaiRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UaeRoute: UaeRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  HolidaysSlugRoute: HolidaysSlugRouteWithChildren,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  HolidaysIndexRoute: HolidaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
